baseURL = "https://beatezirdzina.github.io/username.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ghostwriter"
publishDir = "docs"


[Params]
    mainSections = ["post"]
    intro = true
    headline = "A Lightweight Peruse in Recommender Systems"
    description = "Because it's 2020 and Scrolling [Insert Site of Choice] is our Only Option At this point"
    github = "https://github.com/BeateZirdzina/username.github.io"
  
    email = "beate.zirdzina@gmail.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2020"
    
[Permalinks]
    post = "/:filename/"

    [[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Contact"
url = "/page/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 4
